/* 
  *   Speech.java generated by speechmod 
 */

package scxmlgen.Modalities;

import scxmlgen.interfaces.IModality;

public enum Speech implements IModality {

    BRIGHT_INC("[target][BRIGHT][action][+][value][]", 1500),
    BRIGHT_DEC("[target][BRIGHT][action][-][value][]", 1500),
    VOLUME_UP("[target][VOLUME][action][+][value][]", 1500),
    VOLUME_DOWN("[target][VOLUME][action][-][value][]", 1500),
    VOLUME_FULL("[target][VOLUME][action][.][value][100]", 1500),
    WORKSPACE_PREV("[target][WORKSPACE][action][MOVE][value][PREV]", 1500),
    WORKSPACE_NEXT("[target][WORKSPACE][action][MOVE][value][NEXT]", 1500),
    MOVE_ALEFT("[target][NOTEPAD][action][MOVE][value][LEFT]", 1500),
    MOVE_ARIGHT("[target][NOTEPAD][action][MOVE][value][RIGHT]", 1500),
    MOVE_ADOWN("[target][NOTEPAD][action][MOVE][value][DOWN]", 1500),
    MOVE_AUP("[target][NOTEPAD][action][MOVE][value][UP]", 1500),
    NOTEPAD("[target][NOTEPAD][action][][value][]", 1500);
    
    
	private String event;
	private int timeout;

	Speech(String m, int time) {
		event = m;
		timeout = time;
	}

	@Override
	public int getTimeOut() {
		return timeout;
	}

	@Override
	public String getEventName() {
		return event;
	}

	@Override
	public String getEvName() {
		return getModalityName().toLowerCase() + event.toLowerCase();
	}

}
